export { default as ForknifeIcon } from './ForknifeIcon';
export { default as NavbarIcon } from './NavbarIcon';
export { default as RightGroupIcons } from './RightGroupIcons';
export { default as SearchIcon } from './SearchIcon';
export { default as SpicyIcon } from './SpicyIcon';
export { default as VeganIcon } from './VeganIcon';
export { default as VegitarianIcon } from './VegitarianIcon';
export { default as AboutusIcon } from './AboutUsIcon';
export {default as AppStoreIcon} from './AppStoreIcone';
export {default as GooglePlayIcon} from './GooglePlayIcon';
export {default as ArrowsIcon} from './arrows.svg';