export { default as RightGroupIcons } from '../components/header/rightGroupIcons';
// export {default as GooglePlayIcon} from './GooglePlayIcon';
export {default as ArrowsIcon} from './arrows.svg';
export { default as SpicyIconCard } from './spicyIconCard.svg';
export { default as ILSIcon } from './ils.svg';
export { default as HamburgerIcon } from './hamburger.svg';
export { default as ForkKnifeIcon } from './forkKnife.svg';
export { default as SearchIcon } from './searchIcon.svg';
export { default as PersonIcon } from './person.svg';
export { default as BagIcon } from './Bag.svg';
export { default as VegitarianIcon } from './vegitarianIcon.svg';
export { default as VeganIcon } from './veganIcon.svg';
export { default as EpicureLogo } from './epicureLogo.svg';
export { default as EpicureLogoDesk } from './epicureLogoDeskFooter.svg';
export { default as EpicureLogoMob } from './epicureLogoMobFooter.svg';
export { default as GooglePlayIcon } from './googlePlayIcon.svg';
export { default as AppStoreIcon } from './appStoreIcon.svg';
