import { columns } from "./columns";
import { DishColumn } from "@/types/columns/dishes.column";
import { DataTable } from "@/components/ui/data-table";
import DataDisplay from "@/components/ui/data-display";

export async function getDishData(): Promise<DishColumn[]> {
    return [
      {
        _id: "d1",
        restaurantId: "728ed52f",
        name: "Spicy Tuna Roll",
        description: "Fresh tuna with a kick of spice wrapped in seaweed and rice. Fresh tuna with a kick of spice wrapped in seaweed and rice Fresh tuna with a kick of spice wrapped in seaweed and rice",
        image: "/dishPage/padkimao.png",
        price: 48,
        dishCategory: "spicy",
        chefName: "Gordon Ramsay",
        restaurantName: "The Golden Spoon",
      },
      {
        _id: "d2",
        restaurantId: "728ed52f",
        name: "Vegan Avocado Salad",
        description: "Sliced avocado with greens and citrus dressing.",
        image: "/dishPage/padkimao2.png",
        price: 39,
        dishCategory: "vegan",
        chefName: "Gordon Ramsay",
        restaurantName: "The Golden Spoon",
      },
      {
        _id: "d3",
        restaurantId: "728ed52f",
        name: "Golden Steak",
        description: "Juicy steak grilled to perfection with golden butter.",
        image: "/dishPage/padkimao3.png",
        price: 89,
        dishCategory: undefined,
        chefName: "Gordon Ramsay",
        restaurantName: "The Golden Spoon",
      },
      {
        _id: "d4",
        restaurantId: "01JY1FXADNPS7HHC1Y6X3SPZXM",
        name: "Urban Falafel Bowl",
        description: "Crispy falafel with hummus and salad.",
        image: "/dishPage/redFarm.png",
        price: 45,
        dishCategory: "vegan",
        chefName: "Ana Martinez",
        restaurantName: "Urban Tastes",
      },
      {
        _id: "d5",
        restaurantId: "01JY1FXADNPS7HHC1Y6X3SPZXM",
        name: "Zesty Chicken Wrap",
        description: "Grilled chicken with zesty sauce in a warm wrap.",
        image: "/dishPage/ta_ma_la_ko.png",
        price: 51,
        dishCategory: undefined,
        chefName: "Ana Martinez",
        restaurantName: "Urban Tastes",
      },
      {
        _id: "d6",
        restaurantId: "01JY1FXADQAPPTPQBPS565XBW5",
        name: "Tempura Shrimp",
        description: "Crispy tempura battered shrimp served with dipping sauce.",
        image: "/dishPage/tamalako2.png",
        price: 58,
        dishCategory: undefined,
        chefName: "Yamato Sato",
        restaurantName: "Sea Breeze",
      },
      {
        _id: "d7",
        restaurantId: "01JY1FXADQAPPTPQBPS565XBW5",
        name: "Seaweed Salad",
        description: "Fresh seaweed with sesame and soy dressing.",
        image: "/dishPage/padkimao3.png",
        price: 32,
        dishCategory: "vegan",
        chefName: "Yamato Sato",
        restaurantName: "Sea Breeze",
      },
      {
        _id: "d8",
        restaurantId: "01JY1FXADQAPPTPQBPS565XBW5",
        name: "Spicy Ramen",
        description: "Noodles in spicy broth with vegetables.",
        image: "/dishPage/padkimao.png",
        price: 49,
        dishCategory: "spicy",
        chefName: "Yamato Sato",
        restaurantName: "Sea Breeze",
      },
      {
        _id: "d9",
        restaurantId: "01JY1FXADQTEJ8J8ZQWAKZRSW8",
        name: "Herb Garden Salad",
        description: "A mix of fresh herbs, greens, and citrus vinaigrette.",
        image: "/dishPage/padkimao2.png",
        price: 42,
        dishCategory: "vegetarian",
        chefName: "Lucia Bianchi",
        restaurantName: "Savory Garden",
      },
      {
        _id: "d10",
        restaurantId: "01JY1FXADQTEJ8J8ZQWAKZRSW8",
        name: "Stuffed Zucchini",
        description: "Zucchini stuffed with herbs, cheese and rice.",
        image: "/dishPage/padkimao3.png",
        price: 47,
        dishCategory: "vegetarian",
        chefName: "Lucia Bianchi",
        restaurantName: "Savory Garden",
      },
      {
        _id: "d11",
        restaurantId: "01JY1FXADRVNKXGAKH9KAVWYCA",
        name: "Rustic Pasta",
        description: "Handmade pasta with rustic tomato and basil sauce.",
        image: "/dishPage/redFarm.png",
        price: 67,
        dishCategory: "vegetarian",
        chefName: "James Thornton",
        restaurantName: "The Rustic Fork",
      },
      {
        _id: "d12",
        restaurantId: "01JY1FXADRVNKXGAKH9KAVWYCA",
        name: "Spicy Rustic Chili",
        description: "Rich chili with beans and house spices.",
        image: "/dishPage/ta_ma_la_ko.png",
        price: 59,
        dishCategory: "spicy",
        chefName: "James Thornton",
        restaurantName: "The Rustic Fork",
      },
      {
        _id: "d13",
        restaurantId: "01JY1FXADSYZ1MKMRC3V9RZZWN",
        name: "Firecracker Dumplings",
        description: "Dumplings filled with spicy chicken and herbs.",
        image: "/dishPage/padkimao.png",
        price: 54,
        dishCategory: "spicy",
        chefName: "Mina Zhang",
        restaurantName: "Fusion Point",
      },
      {
        _id: "d14",
        restaurantId: "01JY1FXADSYZ1MKMRC3V9RZZWN",
        name: "Vegan Curry Bowl",
        description: "Coconut curry with tofu and vegetables.",
        image: "/dishPage/redFarm.png",
        price: 53,
        dishCategory: "vegan",
        chefName: "Mina Zhang",
        restaurantName: "Fusion Point",
      },
      {
        _id: "d15",
        restaurantId: "01JY1FXADSYZ1MKMRC3V9RZZWN",
        name: "Mango Sticky Rice",
        description: "Sweet mango with coconut sticky rice.",
        image: "/dishPage/padkimao3.png",
        price: 35,
        dishCategory: undefined,
        chefName: "Mina Zhang",
        restaurantName: "Fusion Point",
      },
    ];
  }
  
  export default async function DishesPage() {
    const data = await getDishData();
    return (
      <div>
        <DataDisplay title="Dishes">
          <DataTable columns={columns} data={data} />
        </DataDisplay>
      </div>
    );
  }